name: PHP Composer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    services:
     mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root1234
          MYSQL_DATABASE: testdb_mvc
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        tools: composer:v2
        extensions: pdo_mysql, memcached # Ensure the PHP memcached extension is installed

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Verify MySQL connection
      run: mysql -h 127.0.0.1 -u root -proot1234 -e "SHOW DATABASES;"

    - name: Start PHP server
      run: |
        php -S 127.0.0.1:8080 -t tests/ & # Assumes your entry point is in the public directory, adjust if needed
        sleep 3 # Give PHP some time to start

    - name: Run PHPUnit tests
      run: ./vendor/bin/phpunit tests